config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'listings#homepage', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'listings#homepage'
  end

  resources :listings

  resources :reservations, only: [:new, :create, :show, :index, :destroy]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users,
    only: [:create, :show, :edit, :update, :destroy] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  if Clearance.configuration.allow_sign_up?
    get "/sign_up" => "clearance/users#new", as: "sign_up"
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates_presence_of :user_id
  validates_presence_of :price
  validates_presence_of :room_type
  validates_presence_of :property_type
  validates_presence_of :bedrooms
  validates_presence_of :bathrooms
  validates_presence_of :guests
  validates_presence_of :title
  validates_presence_of :about
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :state
  # validates_presence_of :zip
  validates_presence_of :country

  mount_uploaders :photos, PhotoUploader

  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :booked_dates, dependent: :destroy


  def self.search(query)
    where(["city ilike ? or country ilike ? or zip ilike ? or state ilike ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%"])
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_listing, only: [:show, :edit, :update, :destroy]

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.build(listing_params)

    if @listing.save
      redirect_to @listing
    else
      flash.now[:error] = @listing.errors.full_messages.first
      render 'new'
    end
  end

  def show
  end

  def homepage
    @listings = Listing.all
  end

  def index
    if params[:search]
      @index_title = "search results for:"
      @search_term = "'#{params[:search]}'"

      @listings = Listing.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 8)
    else
      @index_title = "My Listings"
      @listings = current_user.listings.all.paginate(page: params[:page], per_page: 8)
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      flash[:success] = "Successfully updated listing."
      redirect_to @listing
    else
      flash.now[:error] = @listing.errors.full_messages.first
      render 'edit'
    end
  end

  def destroy
    @listing.destroy
    flash[:success] = "Successfully deleted listing."
    redirect_to root_path
  end


  private

  def find_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :about, :price, :room_type, :property_type, :bedrooms, :bathrooms, :guests, :address, :city, :state, :zip, :country, {photos: []}, :photos_cache, :remove_photos )
  end

end

app/helpers/listings_helper.rb
module ListingsHelper

  def popular_search_for(location)
    listings_path + "?search=" + location.to_s
  end

end

app/views/listings/_form.html.erb
<div class="form-group ">
  <%= form.label :title %>
  <%= form.text_field :title, type: "text", class: "form-control", placeholder: "listing title", required: true %>
</div>



<div class="form-group ">
  <%= form.label :about %>
  <%= form.text_area :about, type: "text", class: "form-control", rows: "6", placeholder: "description of property", required: true %>
</div>

<div class="form-group ">
  <%= form.label :price, "USD $/night" %>
  <%= form.text_field :price, type: "number", min: "1", step: "1", class: "form-control", placeholder: "95", required: true %>
</div>

<div class="form-group ">
  <%= form.label :photos %>
  <% if @listing.photos? %>
    <br>
    <% @listing.photos.each_with_index do |photo| %>
      <%= image_tag photo.url(:small).to_s, class: "img-rounded img-thumbnail img-responsive" %>
    <% end %>
  <% end %>
  <%= form.file_field :photos, multiple: true %>
  <%= form.hidden_field :photos_cache %>
  <br>
  <%= form.check_box :remove_photos %>
  <%= form.label :remove_photos %>
</div>

<br>

<div class="row">
  <div class="col-xs-6">
    <div class="form-group ">
      <%= form.label :property_type %>
      <%= form.select :property_type, ['Apartment', 'House', 'Bed & Breakfast'], required: true %>
    </div>
  </div>

  <div class="col-xs-6">
    <div class="form-group ">
      <%= form.label :room_type %>
      <%= form.select :room_type, ['Entire home/apt', 'Private room', 'Shared room'], required: true %>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-xs-4">
    <div class="form-group ">
      <%= form.label :bedrooms %>
      <%= form.select :bedrooms, [1,2,3,4,5], required: true %>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="form-group ">
      <%= form.label :bathrooms %>
      <%= form.select :bathrooms, [1,2,3,4,5], required: true %>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="form-group ">
      <%= form.label :guests %>
      <%= form.select :guests, [1,2,3,4,5,6,7,8], class: "form-control", required: true %>
    </div>
  </div>
</div>

<div class="form-group ">
<%= form.label :address %>
<%= form.text_area :address, type: "text", class: "form-control", placeholder: "unit number and street address", required: true %>
</div>

<div class="form-group ">
  <%= form.label :city %>
  <%= form.text_field :city, type: "text", class: "form-control", placeholder: "city", required: true %>
</div>

<div class="form-group ">
  <%= form.label :state %>
  <%= form.text_field :state, type: "text", class: "form-control", placeholder: "state/province", required: true %>
</div>

<div class="form-group ">
  <%= form.label :zip %>
  <%= form.text_field :zip, type: "text", placeholder: "zipcode", class: "form-control" %>
</div>

<div class="form-group ">
  <%= form.label :country %>
  <%= form.text_field :country, type: "text", class: "form-control", placeholder: "country", required: true %>
</div>

app/views/listings/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-7 col-md-offset-3 col-lg-6 col-lg-offset-3" id="listing">
  <center>
    <h2><%= t(".edit_listing") %></h2>
  </center>

  <%= form_for @listing do |form| %>

    <%= render partial: '/listings/form', object: form %>

    <%= button_tag type: "submit", class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-ok"></i> Update listing
    <% end %>

    <div class="pull-right">
      <%= link_to '<i class="glyphicon glyphicon-remove"></i> Cancel'.html_safe, listing_path, class: "btn btn-danger" %>
    </div>

  <% end %>

  </div>
</div>

app/views/listings/homepage.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Find a place to stay.</h1>
    <p>Rent from people in over 34,000 cities and 192 countries.</p>
    <br>
    <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">

      <%= form_tag(listings_path, method: "get", id: "search-form", enforce_utf8: false) do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Where do you want to go?" %>
          <div class="input-group-btn">
              <button class="btn" type="submit">&nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-search"></span> Search&nbsp;&nbsp;&nbsp;&nbsp;</button>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

<div class="explore">
  <div class="container">
    <center>
      <h2>Explore the world</h2>
      <p>Discover new, inspiring places close to home.</p>
      <div class="row">
        <div class="col-sm-4">
          <%= link_to popular_search_for("london") do %>
            <%= image_tag("london.png", class:"img-responsive") %>
          <% end %>
        </div>
        <div class="col-sm-4">
          <%= link_to popular_search_for("ubud") do %>
            <%= image_tag("ubud.png", class:"img-responsive") %>
          <% end %>
        </div>
        <div class="col-sm-4">
          <%= link_to popular_search_for("rome") do %>
            <%= image_tag("rome.png", class:"img-responsive") %>
          <% end %>
        </div>
      </div>
      <br>
      <div class="row hidden-xs">
        <div class="col-sm-4">
          <%= link_to popular_search_for("tokyo") do %>
            <%= image_tag("tokyo.png", class:"img-responsive") %>
          <% end %>
        </div>
        <div class="col-sm-4">
          <%= link_to popular_search_for("sydney") do %>
            <%= image_tag("sydney.png", class:"img-responsive") %>
          <% end %>
        </div>
        <div class="col-sm-4">
          <%= link_to popular_search_for("bangkok") do %>
            <%= image_tag("bangkok.png", class:"img-responsive") %>
          <% end %>
        </div>
      </div>
    </center>
  </div>
</div>

<div class="learn-more">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h3>Travel</h3>
        <p>From apartments and rooms to treehouses and boats: stay in unique spaces in 192 countries.</p>
        <p><a href="#">See how to travel on Airbnb</a></p>
      </div>
      <div class="col-md-4">
        <h3>Host</h3>
        <p>Renting out your unused space could pay your bills or fund your next vacation.</p>
        <p><a href="#">Learn more about hosting</a></p>
      </div>
      <div class="col-md-4">
        <h3>Trust and Safety</h3>
        <p>From Verified ID to our worldwide customer support team, we've got your back.</p>
        <p><a href="#">Learn about trust at Airbnb</a></p>
      </div>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h2><%= @listings.count %>&nbsp;<%= @index_title %>&nbsp;<small><span class= "label label-info"><%= @search_term %></small></span> </h2>
      </div>
      <!-- <p>A snippet I recently used to display homes for a local brokerage.  Focused more on images when accessed through mobile</p> -->
    </div><!-- col-md-12 -->
  </div><!-- row -->
</div>

<div class="container" id="listings">
  <div class="row">
    <% if @listings.count == 0 %>
      <div class="col-md-12">
        <h4>No listings found, <%= link_to "click here to search again.", root_path %></h4>
      </div>
    <% else %>

      <% @listings.each do |listing| %>
        <div class="col-sm-6 col-md-12 col-lg-6">
          <div class="listing">
            <div class="media">
              <% if listing.photos.empty? %>
                <%= link_to image_tag("http://placehold.it/340x200&text=no photos for listing", class: "img-responsive"), listing_path(listing), data: { no_turbolink: true }, class: "pull-left" %>
              <% else %>
                <%= link_to image_tag(listing.photos[0].url(:small).to_s, class: "img-responsive"), listing_path(listing), data: { no_turbolink: true }, class: "pull-left" %>
              <% end %>
              <div class="clearfix visible-sm"></div>
              <!-- pushes text below the picture -->

              <div class="media-body">
                <br class="hidden-md hidden-lg">
                <h3 class="media-heading">
                  <span class="label label-info pull-right">$<%= listing.price %></span>
                  <small><%= listing.city %>, <%= listing.country %></small>
                  <div class="clearfix"></div>

                  <span class="listing_title"><%= link_to listing.title.first(60), listing_path(listing), data: { no_turbolink: true } %></span>
                </h3>

                <p>
                  <%= listing.room_type %>&nbsp;&nbsp;|&nbsp;&nbsp;<span class="badge"><%= listing.bedrooms %></span> Bedrooms&nbsp;&nbsp;|&nbsp;&nbsp;<span class="badge"><%= listing.bathrooms %></span> Baths
                </p>

                <p class="hidden-xs">
                  <%= listing.about.first(127) %>
                </p>
                <p class="hidden-sm hidden-md hidden-lg">
                  <%= listing.about.first(100) %>
                </p>

              </div><!-- media-body -->
            </div><!-- media -->
          </div><!-- listing-->
        </div><!-- col-sm-6 -->
      <% end %><!-- listing.each -->

    <% end %><!-- if listing.count -->
  </div><!-- row -->
</div><!-- container -->
<center>
  <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</center>
<br>

app/views/listings/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-7 col-md-offset-3 col-lg-6 col-lg-offset-3" id="listing">
  <center>
    <h2><%= t(".new_listing") %></h2>
  </center>

  <%= form_for @listing, html: { multipart: true } do |form| %>

    <%= render partial: '/listings/form', object: form %>

    <%= button_tag type: "submit", class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-ok"></i> Create listing
    <% end %>

    <div class="pull-right">
      <%= link_to '<i class="glyphicon glyphicon-remove"></i> Cancel'.html_safe, root_path, class: "btn btn-danger" %>
    </div>

  <% end %>

  </div>
</div>

app/views/listings/show.html.erb
<% content_for :stylesheets do %>

  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

<% end %>

<div class="row">
  <div class="col-sm-12 col-md-11 col-lg-10 col-lg-offset-1" id="listing">

    <div class="row">
      <% if signed_in? && (current_user.id == @listing.user.id) %>
        <br>
        <div class="pull-left">
          <%= link_to '<i class="glyphicon glyphicon-tags"></i>&nbsp;&nbsp;Reservations for listing'.html_safe, reservations_path(listing_id: @listing.id), class: "btn btn-primary" %>
        </div>
        <div class="pull-right">
          <%= link_to '<i class="glyphicon glyphicon-wrench"></i>&nbsp;&nbsp;Edit'.html_safe, edit_listing_path, class: "btn btn-success" %>

          <%= link_to '<i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;Delete'.html_safe, listing_path, method: :delete, data: {
              confirm: 'Are you sure you want to delete this listing?',
              :'confirm-button-text' => 'Yes, delete it',
              :'cancel-button-text' => 'No, go back',
              :'confirm-button-color' => '#66CD00',
              :'sweet-alert-type' => 'info',
              }, class: "btn btn-danger" %>
        </div>
        <br>
        <hr>
      <% end %>
      <!-- <center> -->
        <div class="page-header">
          <h2><%= @listing.title %>
            <div class="pull-right">
              <small><%= @listing.city %>, <%= @listing.country %></small>
            </div>
          </h2>
        </div>
      <!-- </center> -->
    </div><!-- row -->

    <!-- Slider -->
    <div class="row">
      <div class="col-xs-12" id="slider">
        <!-- Top part of the slider -->
        <div class="row">
          <div class="col-sm-8" id="carousel-bounding-box">
            <div class="carousel slide" id="myCarousel">
              <!-- Carousel items -->
              <div class="carousel-inner">
                <% unless @listing.photos.empty? %>
                  <% @listing.photos.each_with_index do |photo, index| %>
                    <% if index == 0 %>
                      <div class="item active" data-slide-number="<%= index %>">
                    <% else %>
                      <div class="item" data-slide-number="<%= index %>">
                    <% end %>
                        <%= image_tag(photo.url(:carousel).to_s) %>
                      </div>
                  <% end %>
                <% else %>
                  <div class="active item" data-slide-number="0">
                    <%= image_tag "http://placehold.it/770x300&text=no photos for listing"%>
                  </div>
                <% end %>

              </div><!-- carousel-inner -->

              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
              </a>
            </div><!-- #myCarousel -->
            <div class="hidden-sm hidden-md hidden-lg">
              <br>
            </div>
          </div> <!-- #carousel-bounding-box -->

          <div class="col-xs-12 col-sm-4 booking" id="carousel-text">
            <div class="col-xs-5 col-sm-12">
              <h4>Cost per night:</h4>
              <div class="input-group">
               <!--  <span class="input-group-addon">USD <span class="glyphicon glyphicon-usd"></span></span> -->
                <input id="readonly" class="form-control" type="text" value="USD $<%= @listing.price %>" readonly>
              </div>
            <br>
            </div>

            <div class="col-xs-7 col-sm-12">
              <h4>Select dates:</h4>
              <%= form_for :reservation, url: new_reservation_path, method: "get", enforce_utf8: false do |form| %>
                <%= form.hidden_field :listing_id, value: @listing.id %>

                <div class="input-group">
                  <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                  <%= form.text_field :daterange, id: "daterange", class: "form-control"%>
                </div>
                <br>
                <center>
                  <%= button_tag type: "submit", class: "btn btn-success btn-lg" do %>
                    <i class="glyphicon glyphicon-circle-arrow-right"></i>&nbsp;&nbsp;Book now
                  <% end %>
                  <!--
                  <button type="submit" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-circle-arrow-right"></span>&nbsp;&nbsp;Book now&nbsp;&nbsp;</button>
                  -->
                </center>
              <% end %>
              <br>
            </div><!-- col-xs-7 -->
          </div><!-- #carousel-text -->

          <div id="slide-content" style="display: none;">

          </div><!-- #slide-content -->
        </div><!-- row -->
      </div><!-- #slider -->
    </div><!-- row -->

    <div class="row hidden-xs" id="slider-thumbs">
      <!-- Bottom switcher of slider -->
      <ul class="hide-bullets">

        <% if @listing.photos? %>
          <% @listing.photos.each_with_index do |photo, index| %>
            <li class="col-sm-2">
              <a class="img-reponsive" id="carousel-selector-<%=index%>" >
                <%= image_tag(photo.url(:thumb).to_s, class:"img-responsive") %>
              </a>
            </li>
          <% end %>
        <% else %>
<!--           <li class="col-sm-2">
            <%= image_tag "http://placehold.it/350x250", class: "img-responsive" %>
          </li> -->
        <% end %>

      </ul>
    </div><!-- #slider-thumbs -->

    <div class="row">
      <div class="col-sm-3">
        <div class="page-header">
          <h4>Address</h4>
        </div>
        <%= @listing.address %><br>
        <%= @listing.city %>, <%= @listing.state %><br>
        <%= @listing.country %> <% @listing.zip %><br>
      </div>
      <div class="col-sm-3">
        <div class="page-header">
          <h4><%= @listing.room_type %></h4>
        </div>
        <span class="badge"><%= @listing.bedrooms %></span> bedrooms<br>
        <span class="badge"><%= @listing.bathrooms %></span> baths<br>
        <span class="badge"><%= @listing.guests %></span> guests
      </div>
      <div class="col-sm-6">
        <div class="page-header">
          <h4>Amenities</h4>
        </div>
        <div class="col-xs-4">
          AMENTIES<br>
          AMENTIES<br>
          AMENTIES<br>
          AMENTIES
        </div>
        <div class="col-xs-4">
          AMENTIES<br>
          AMENTIES<br>
          AMENTIES<br>
          AMENTIES
        </div>
        <div class="col-xs-4">
          AMENTIES<br>
          AMENTIES<br>
          AMENTIES
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="page-header">
          <h4>About</h4>
        </div>
        <%= @listing.about %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="page-header">
          <h4>Location</h4>
        </div>
        <div id="map"></div>

      </div>
    </div>
  </div><!-- #listing -->
</div><!-- row -->

<% content_for :javascript do %>
  <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvxDulYD_MO48MXUKk-mtwG9tS-k5ou1U&libraries=visualization&callback=initMap">
  </script>

  <script type="text/javascript">
    $('#myCarousel').carousel({
      interval: 5000
    });

    $('#carousel-text').html($('#slide-content-0').html());

    //Handles the carousel thumbnails
    $('[id^=carousel-selector-]').click( function(){
      var id = this.id.substr(this.id.lastIndexOf("-") + 1);
      var id = parseInt(id);
      $('#myCarousel').carousel(id);
    });

    // When the carousel slides, auto update the text
    $('#myCarousel').on('slid.bs.carousel', function (e) {
      var id = $('.item.active').data('slide-number');
      $('#carousel-text').html($('#slide-content-'+id).html());
    });

    $("#daterange").daterangepicker({
      "autoApply": true,
      "opens": "left",
      // isInvalidDate: function( date ) {
      //  if( date.date() === 1 ) {
      //    return true;
      //  } else {
      //    return false;
      //  }
      // }
    });

    $("#daterange").on("apply.daterangepicker", function(ev, picker) {
      // console.log(picker.startDate.format("YYYY-MM-DD"));
      var start = picker.startDate.format("YYYY-MM-DD");

      // console.log(picker.endDate.format("YYYY-MM-DD"));
      var end = picker.endDate.format("YYYY-MM-DD");
    });

    // Google Maps
    function initMap() {
      // console.log("GOOGLE MAPS LAH");

      var myLatLng = {lat: 34.012197, lng: -117.859657};

      var map = new google.maps.Map(document.getElementById('map'), {
        center: myLatLng,
        zoom: 14,
        styles: [{
          featureType: 'poi',
          stylers: [{ visibility: 'off' }]  // Turn off points of interest.
        }, {
          featureType: 'transit.station',
          stylers: [{ visibility: 'off' }]  // Turn off bus stations, train stations, etc.
        }],
        disableDoubleClickZoom: true
      });

      var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: '<%= @listing.address %>'
        });
    }

  </script>

<% end %>