config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'listings#homepage', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'listings#homepage'
  end

  resources :listings

  resources :reservations, only: [:new, :create, :show, :index, :destroy]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users,
    only: [:create, :show, :edit, :update, :destroy] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  if Clearance.configuration.allow_sign_up?
    get "/sign_up" => "clearance/users#new", as: "sign_up"
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates_presence_of :user_id
  validates_presence_of :listing_id
  validates_presence_of :start_date
  validates_presence_of :end_date
  validates_uniqueness_of :start_date, scope: :end_date, message: "cannot be the same as end date."
  validate :start_date_cannot_be_in_the_past

  belongs_to :user
  belongs_to :listing
  has_many :booked_dates, dependent: :destroy

  # allow @dates instance variable to be passed back to Reservation controller
  attr_accessor :dates

  def start_date_cannot_be_in_the_past
    if start_date < Date.today
      errors.add(:start_date, " can't be in the past.")
    end
  end


  def dates_available?(start_date, end_date)
    # find all dates between start/end dates
    @dates = (start_date..end_date).map(&:to_s)

    # remove last date since new booking can be made on same day as late date
    @dates.pop

    #check each date against booked_dates table
    @dates.each do |search_date|

      # if date = booked_date
      if listing.booked_dates.where("date = ?", search_date).present?

        # return dates_available? = false
        return false
        break
      else
        # else return dates_available? = true
        return true
      end

    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :require_login, only: [:new, :create, :show, :index, :destroy]
  before_action :find_reservation, only: [:show, :destroy]

  def new
    @listing = Listing.find(reservation_params[:listing_id])

    # check if current_user trying to book his own listing
    if (current_user.id == @listing.user.id)
      flash[:error] = "You cannot book your own listing."
      redirect_to @listing
    else
      daterange = reservation_params[:daterange]
      # split the dates & parse them to YYYY-MM-DD format
      start_date, end_date = daterange.split(" - ")

      @start_date = Date.parse(start_date).strftime("%Y-%m-%d")
      @end_date = Date.parse(end_date).strftime("%Y-%m-%d")

      if @start_date == @end_date
        flash[:error] = "Check-out date can't be the same as check-in date."
        redirect_to @listing
      else

        # dates = {start_date: start_date, end_date: end_date}

        # remove :daterange from reservation_params
        # reservation_params.delete_if{ | key,value | key == "daterange"}

        # add start_date, end_date to reservation_params
        # reservation_params.merge!(dates)
        reservation = current_user.reservations.build(listing_id: reservation_params[:listing_id], start_date: @start_date, end_date: @end_date)

        unless reservation.dates_available?(@start_date, @end_date)

          flash[:error] = "Your selected dates of #{@start_date.to_date.to_formatted_s(:long)} to #{@end_date.to_date.to_formatted_s(:long)} are not available for booking."
          redirect_to @listing

        end # dates_available? check
      end # start_date = end_date check
    end # current_user self booking check

  end

  def create
    listing = Listing.find(reservation_params[:listing_id])

    @reservation = current_user.reservations.build(listing_id: reservation_params[:listing_id], start_date: params[:reservation][:start_date], end_date: params[:reservation][:end_date])

    if @reservation.save
        # find all dates between start/end dates
        @reservation.dates = (@reservation.start_date..@reservation.end_date).map(&:to_s)

        # remove last date since new booking can be made on same day as late date
        @reservation.dates.pop

        @reservation.dates.each do |date|
          # created booked_dates table entries
          @reservation.booked_dates.create(listing_id: reservation_params[:listing_id], date: date)
        end

      # call the job using activejob sidekiq
      BookingEmailJob.perform_later(@reservation)

      flash[:success] = "Reservation succesfully booked. Please check your email for confirmation."
      redirect_to @reservation
    else
      flash[:error] = @reservation.errors.full_messages.first
      redirect_to listing
    end # @reservation.save

  end # create

  def show
  end

  def index
    if params[:listing_id]
      listing = Listing.find(params[:listing_id])
      @reservations = listing.reservations.all
      @index_title = "Reservations for: #{listing.title}"
      @owner_viewing = true
    else
      @reservations = current_user.reservations.all
      @index_title = "My Reservations"
      @owner_viewing = false
    end
  end

  def destroy
    # call the job using sidekiq
    CancellationEmailJob.perform_later(@reservation.listing.title, @reservation.user, @reservation.listing.id)

    @reservation.destroy
    flash[:success] = "Successfully cancelled reservation. Please check your email for confirmation."
    redirect_to reservations_path
  end

  private

  def find_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:listing_id, :daterange)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<% content_for :stylesheets do %>

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.0.2/css/responsive.bootstrap.min.css"/>

<% end %>

<div class="container" id="reservations">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h2><%= @index_title %></h2>
      </div>
      <!-- <p>A snippet I recently used to display homes for a local brokerage.  Focused more on images when accessed through mobile</p> -->
    </div><!-- col-md-12 -->
  </div><!-- row -->
  <div class="row">
    <% if @reservations.count == 0 %>
      <div class="col-md-12">
        <h4>No reservations found, <%= link_to "click here to search listings.", root_path %></h4>
      <% else %>
        <table class="table table-striped table-bordered dt-responsive nowrap" id="reservations_table" cellspacing="10" width="100%">
          <thead>
            <tr>
              <th>Booking date</th>
              <th>From</th>
              <th>To</th>
              <% if @owner_viewing %>
                <th>Renter</th>
              <% else %>
                <th>Listing</th>
              <% end %>
              <th>City, Country</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @reservations.each do |reservation| %>
            <tr>
              <td><%= reservation.created_at.to_formatted_s(:long) %></td>
              <td><%= reservation.start_date.to_formatted_s(:long) %></td>
              <td><%= reservation.end_date.to_formatted_s(:long) %></td>
              <% if @owner_viewing %>
                <td><%= reservation.user.email %></td>
              <% else %>
                <td><%= link_to reservation.listing.title, listing_path(reservation.listing), data: { no_turbolink: true } %></td>
              <% end %>
              <td><%= reservation.listing.city %>, <%= reservation.listing.country %></td>
              <td>
              <%= link_to '<i class="glyphicon glyphicon-search"></i>&nbsp;&nbsp;View'.html_safe, reservation_path(reservation), class: "btn btn-primary" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>

      <% end %>
      <br>
      <br>

    </div><!-- col-sm -->
  </div><!-- row -->
</div><!-- reservations -->

<% content_for :javascript do %>

  <script type="text/javascript" src="https://cdn.datatables.net/t/dt/dt-1.10.11/datatables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.0.2/js/responsive.bootstrap.min.js"></script>

  <script type="text/javascript">

    $("#reservations_table").DataTable({
      "order": [[ 0, "asc" ]],
      responsive: true,
      "pageLength": 8,
      columnDefs: [
        { responsivePriority: 6, targets: 0 },
        { responsivePriority: 4, targets: -1 }
      ]
    });

  </script>

<% end %>

app/views/reservations/new.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2" id="reservation">
    <div class="page-header">
      <h3>Reservation details</h3>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <% if @listing.photos.empty? %>
          <%= image_tag "http://placehold.it/770x300&text=no images for listing", class:"img-responsive" %>
        <% else %>
          <%= image_tag(@listing.photos[0].url(:carousel).to_s, class:"img-responsive") %>
        <% end %>
        <div class="page-header">
          <h4><%= link_to @listing.title, listing_path(@listing), data: { no_turbolink: true } %></h4>
        </div>
        <%= @listing.about %>
      </div>
      <div class="col-sm-6">
        <div class="hidden-sm hidden-md hidden-lg">
          <br>
        </div>

        <strong>Check-in: </strong><%= @start_date.to_date.to_formatted_s(:long) %>
        <hr>
        <strong>Check-out: </strong><%= @end_date.to_date.to_formatted_s(:long) %>
        <hr>
        <div class="row">
          <div class="col-xs-3">
            <strong>Address:</strong>
          </div>
          <div class="col-xs-9">
            <%= @listing.address %><br>
            <%= @listing.city %>, <%= @listing.state %><br>
            <%= @listing.country %> <%= @listing.zip %><br>
          </div>
        </div><!-- row -->
        <hr>
        <div class="price">
          <h3>Total cost for <%= pluralize((@end_date.to_date - @start_date.to_date).to_i, 'night') %>: $<%= @listing.price * (@end_date.to_date - @start_date.to_date).to_i %></h3>
          <br>
        <strong>Payment method:</strong> Visa / Mastercard
        </div>
        <br>
        <div class="pull-left">
          <%= link_to '<i class="glyphicon glyphicon-remove"></i>&nbsp;&nbsp;Cancel'.html_safe, @listing, data: { no_turbolink: true }, class: "btn btn-danger" %>
        </div>
        <%= form_for :reservation, url: reservations_path do |form| %>
          <%= form.hidden_field :listing_id, value: @listing.id %>
          <%= form.hidden_field :start_date, value: @start_date %>
          <%= form.hidden_field :end_date, value: @end_date %>
          <div class="pull-right">
            <%= button_tag type: "submit", class: "btn btn-success" do %>
              <i class="glyphicon glyphicon-ok"></i>&nbsp;&nbsp;Complete booking
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <br>
    <br>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2" id="reservation">
    <div class="page-header">
      <h3>Reservation details</h3>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <% if @reservation.listing.photos.empty? %>
          <%= image_tag "http://placehold.it/770x300&text=no images for listing", class:"img-responsive" %>
        <% else %>
          <%= image_tag(@reservation.listing.photos[0].url(:carousel).to_s, class:"img-responsive") %>
        <% end %>
        <div class="page-header">
        <h4><%= link_to @reservation.listing.title, listing_path(@reservation.listing), data: { no_turbolink: true } %></h4>
        </div>
        <%= @reservation.listing.about %>
      </div>
      <div class="col-sm-6">
        <div class="hidden-sm hidden-md hidden-lg">
          <br>
        </div>
        <strong>Your Payment ID: </strong> #105152396140
        <hr>
        <strong>Check-in: </strong><%= @reservation.start_date %>
        <hr>
        <strong>Check-out: </strong><%= @reservation.end_date %>
        <hr>
        <div class="row">
          <div class="col-xs-3">
            <strong>Address:</strong>
          </div>
          <div class="col-xs-9">
            <%= @reservation.listing.address %><br>
            <%= @reservation.listing.city %>, <%= @reservation.listing.state %><br>
            <%= @reservation.listing.country %> <%= @reservation.listing.zip %><br>
          </div>
        </div><!-- row -->
        <hr>
        <div class="price">
          <h3>Total cost for <%= pluralize((@reservation.end_date-@reservation.start_date).to_i, 'night') %>: $<%= @reservation.listing.price * (@reservation.end_date - @reservation.start_date).to_i %></h3>
        </div>
      </div>
    </div>

    <div class="row">
      <% if signed_in? && (current_user.id == @reservation.user.id) %>
      <hr>
        <div class="pull-left">

        </div>
        <div class="pull-right">

          <%= link_to '<i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;Cancel reservation'.html_safe, reservation_path, method: :delete, data: {
              confirm: 'Are you sure you want to cancel this reservation?',
              :'confirm-button-text' => 'Yes, cancel it',
              :'cancel-button-text' => 'No, go back',
              :'confirm-button-color' => '#66CD00',
              :'sweet-alert-type' => 'info',
              }, class: "btn btn-danger" %>

        </div>
      <% end %>
    </div><!-- row -->

    <br>
    <br>
  </div>
</div>