config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'listings#homepage', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'listings#homepage'
  end

  resources :listings

  resources :reservations, only: [:new, :create, :show, :index, :destroy]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users,
    only: [:create, :show, :edit, :update, :destroy] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  if Clearance.configuration.allow_sign_up?
    get "/sign_up" => "clearance/users#new", as: "sign_up"
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">

    <% flash.each do |type, message| %>
      <br>
      <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= message %>
      </div>
    <% end %>

  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'PairBnB', root_path, class: 'navbar-brand', html: "h1" %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div><!-- .navbar-header -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if signed_in? %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li>
            <%= link_to '<i class="glyphicon glyphicon-picture"></i>&nbsp;&nbsp;Create new listing'.html_safe, new_listing_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to listings_path do %>
                  <%= content_tag :span, "  ", class: "glyphicon glyphicon-home" %>
                  <%= content_tag :span, "My listings  " %>
                  <%= content_tag :span, "#{current_user.listings.count}", class: "badge" %>
                <% end %>
              </li>
              <li>
                <%= link_to reservations_path, data: { no_turbolink: true } do %>
                  <%= content_tag :span, "  ", class: "glyphicon glyphicon-home" %>
                  <%= content_tag :span, "My reservations  " %>
                  <%= content_tag :span, "#{current_user.reservations.count}", class: "badge" %>
                <% end %>
              </li>
              <li class="divider"></li>
                <li><%= link_to '<i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp;Profile'.html_safe %></li>
            </ul>
          </li><!-- dropdown -->
          <%= link_to '<i class="glyphicon glyphicon-log-out"></i>&nbsp;&nbsp;Logout'.html_safe, sign_out_path, method: :delete, class: "btn btn-default navbar-btn" %>
        <% else %>
          <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i>&nbsp;&nbsp;Login'.html_safe, sign_in_path %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp;Signup'.html_safe, sign_up_path %></li>
        <% end %>
      </ul>
    </div><!-- .navbar-collapse -->
  </div><!-- .container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <title>PairBnB</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= yield :stylesheets %>

  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: '/layouts/navbar' %>

  <div class="container-fluid">

    <%= render partial: '/layouts/flash' %>

  </div>

  <%= yield %>

  <footer>
    Made with <span class="glyphicon glyphicon-heart"></span> by <a href="http://www.natewelling.com" target="_blank">Nate Welling</a>
  </footer>

  <%= yield :javascript %>
</body>
</html>